### ISSUE TITLE
Restrict project name: Too long job names possible

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#101]
job name max length: 40, the template will be broken if the project name is long (`jupyter-{project-name}`)

**Comment by mariyadavydova** [comment]
This means that the project slug may not be longer than 28 chars, i.e. 40 - length("tensorboard-"). Is it possible to enforce the restriction in Cookiecutter?

**Comment by anayden** [comment]
We can have a post-create hook that validates project slug is okay and prints an error message and aborts project creation.

Also we can use `project_slug[:28]` instead project slug in the project, but this would be an implicit thing - user would type longer string, but we would use shorter one.

What's better? @mariyadavydova

**Comment by ayushkovskiy** [comment]
I agree with usage of pre-hooks (not post-hooks; it's the vanilla example in the cookiecutter tutorial: https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html)
