### ISSUE TITLE
Idea: use cookiecutter hooks

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#104]
Cookiecutter allows to write pre- and post-baking hooks: https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html

May be used for:
1. pre-hook: validate project name
2. post-hook: if the user has chosen empty license, then delete empty LICENSE file generated during baking.

Thanks @asvetlov for this idea.

**Comment by mariyadavydova** [comment]
Oh, that's an amazing idea! It should also help with issues like #103.

**Comment by anayden** [comment]
And #101, I just put a comment there about this exact thing :)

**Comment by anayden** [comment]
Used in #122
