### ISSUE TITLE
Decide our policy w.r.t. jupyter checkpoints

### ISSUE THREAD

**Issue by yartem** [neuromation/cookiecutter-neuro-project#110]
Should we upload and rewrite the file `/project/notebooks/.ipynb_checkpoints`, or we should ignore it so that each `make jupyter` is bare clean?

**Comment by mariyadavydova** [comment]
What kind of information is contained in these files?

**Comment by ayushkovskiy** [comment]
It's kinda simplistic version control: https://stackoverflow.com/questions/46421663/what-are-jupyter-notebook-checkpoint-files-for#comment86934059_46422176

**Comment by yartem** [comment]
ignored in https://github.com/neuromation/cookiecutter-neuro-project/pull/381
