### ISSUE TITLE
requirements.txt: do not fix versions of base pip dependencies

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#117]
they are already fixed in base template: https://github.com/neuromation/template-base-image/blob/ca9f7cae744fb0769197c1b015b4835299583ca5/targets/Dockerfile.python36-jupyter-pytorch-tensorflow-jupyterlab#L98-L102

So we'll have difficulties if versions differ.

**Comment by mariyadavydova** [comment]
This is true. We should have exactly the same list of dependencies in base image and in requirements.txt.

**Comment by ayushkovskiy** [comment]
let's better do https://github.com/neuromation/cookiecutter-neuro-project/pull/136#issuecomment-544491778
