### ISSUE TITLE
Remove inter-target dependencies

### ISSUE THREAD

**Issue by yartem** [neuromation/cookiecutter-neuro-project#118]
Honestly, I would change the development strategy of `Makefile` "type less" to "have more control via independent targets". 

We have public targets like `make upload` that do upload user code to Storage. Then, the target `make jupyter` (which, in fact, should just run jupyter notebook) again runs `make upload-code` and `make upload-notebooks`, which takes on `dev` on empty project around 1 minute to connect to the cluster, check that the content of every file is up-to-date, etc. 

I think, our commands should  do *exactly what they tell us they do*, and the users should manually upload code to the Storage. As a bonus argument, this is the way they are taught to look into `make upload` commands and see that they use `neuro cp`.

NB: Note, that currently no targets depend on `make setup`, however in fact they do.

**Comment by mariyadavydova** [comment]
I agree. For me, it makes perfect sense that I have to set up the environment, then upload data, then upload code, then run jupyter/training/file browser/etc.

**Comment by anayden** [comment]
I like the idea, but I guess @astaff wanted to keep dependencies as is. Perhaps, we could have two versions of makefile or two types of targets: "automated" targets (that include uploads) and "manual" ones (that only do what they tell us to do).

On the side note _commands should do exactly what they tell us they do_ seems to contradict with the make philosophy — on of the primary reasons to use makefiles is to run multiple dependent targets when a parent one is called.

**Comment by mariyadavydova** [comment]
> the primary reasons to use makefiles is to run multiple dependent targets when a parent one is called

I can't agree more when we talk about code-related targets. However, in our case, we work with a remote server, so uploading unchanged code several times is frustrating. 

Can't we actually use Makefile mechanisms to depend on the content of the uploaded directories (for `upload-XXX` goals) and files with requirements (for `setup` goal)?

**Comment by mariyadavydova** [comment]
AFAIU Makefiles, they compare the timestamp of dependencies with the timestamp of the goal, so that we need to have some dummy files for a goal to make it work. 

So, for `setup`, we can create a hidden file ('.setup') as a goal output and make the target depending on `requirements.txt` and `apt.txt`.

For code and notebooks, I see that
>which takes on dev on empty project around 1 minute to connect to the cluster, check that the content of every file is up-to-date, etc.
We should check how much it takes on staging (several seconds before running Jupyter are not that much).

As for data, I'm not sure what to do. Jobs depend on this folder, too, but checking if it is up to date may take too much time.

**Comment by ayushkovskiy** [comment]
I up-vote this issue again: When there's a lot of data, it takes a lot of time of uploading the dataset! I think, since we have public targets to upload things, they should not be dependent on.

**Comment by AlekseySh** [comment]
As for me, dependencies in nakefile is ok. (But I never change code on the platform)

**Comment by ayushkovskiy** [comment]
see https://github.com/neuromation/cookiecutter-neuro-project/pull/204#discussion_r354462076
