### ISSUE TITLE
Get rid of `--network-timeout=300`

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#120]
`neuro`'s global option `--network-timeout` specifies the timeout between two reads, not the overall timeout. Thus, we allow our commands used in `neuro exec` (in `make setup`) to keep silence for 5 minutes! comparing to default 1 minute. This is not what we need, in addition, we overcomplicate commands syntax. 

AFAIR, we added `--network-timeout=300` as an emergency option right before the first demo. Now we have time to investigate this question more thoroughly and, if needed, increase the default timeout in `neuro` instead (cc @asvetlov).

**Comment by mariyadavydova** [comment]
AFAIR, this option is no longer valid and should be removed anyway.
