### ISSUE TITLE
Makefile: Most env variables should be non-overridable (`=` instead of `?=`)

### ISSUE THREAD

**Issue by yartem** [neuromation/cookiecutter-neuro-project#124]
these env vars should be env-var-configurable (with `?=`):
https://github.com/neuromation/cookiecutter-neuro-project/blob/e520db5964161c376754896600f9a46cb0a1d8ab/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L1-L6

but these vars derived from those should use `=`:
https://github.com/neuromation/cookiecutter-neuro-project/blob/e520db5964161c376754896600f9a46cb0a1d8ab/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L7-L13

**Comment by ayushkovskiy** [comment]
Note: maybe non-lazy variable set is better: ` := `
