### ISSUE TITLE
Get rid of `-e PLATFORMAPI_SERVICE_HOST="."`

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#153]
We need to harmonize cookiecutter with the updated docker image: https://github.com/neuromation/template-base-image/pull/33/

replace this with `-e EXPOSE_SSH=yes` 
https://github.com/neuromation/cookiecutter-neuro-project/blob/dc9f09a24479a8b9f3845a5ec23cd66304cd0820/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L69

(only for those jobs that need SSH)

**Comment by mariyadavydova** [comment]
Actually, there are no jobs that require SSH in this particular template. I suggest to remove this line everywhere. I will add the parameter and the corresponding job later, when writing a tutorial.

**Comment by ayushkovskiy** [comment]
OK
