### ISSUE TITLE
Makefile: reduce .gitignore

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#170]
Too much trash now: https://github.com/neuromation/cookiecutter-neuro-project/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.gitignore

**Comment by ayushkovskiy** [comment]
To be thrown away:

https://github.com/neuromation/cookiecutter-neuro-project/blob/06aee7e4a384ea1d481b80f738331f97b2de10f6/%7B%7Bcookiecutter.project_slug%7D%7D/.gitignore#L42-L76

https://github.com/neuromation/cookiecutter-neuro-project/blob/06aee7e4a384ea1d481b80f738331f97b2de10f6/%7B%7Bcookiecutter.project_slug%7D%7D/.gitignore#L81-L83

https://github.com/neuromation/cookiecutter-neuro-project/blob/06aee7e4a384ea1d481b80f738331f97b2de10f6/%7B%7Bcookiecutter.project_slug%7D%7D/.gitignore#L88-L104

https://github.com/neuromation/cookiecutter-neuro-project/blob/06aee7e4a384ea1d481b80f738331f97b2de10f6/%7B%7Bcookiecutter.project_slug%7D%7D/.gitignore#L106-L126

And either remove from gitignore `.idea/` , or add other popular IDEs.

And add a "section" of project-specific gitignores (i.e., rename this: https://github.com/neuromation/cookiecutter-neuro-project/blob/06aee7e4a384ea1d481b80f738331f97b2de10f6/%7B%7Bcookiecutter.project_slug%7D%7D/.gitignore#L128

**Comment by ayushkovskiy** [comment]
and instead of `data` dir stays at the project's root, i.e. hsould be `/data/**/*`

**Comment by mariyadavydova** [comment]
I suppose that this file was generated automatically by some tool generating excludes for Python projects. Why do you think that having all this line there is a problem?

**Comment by ayushkovskiy** [comment]
No, they were taken from the standard Python .gitignore file: https://github.com/github/gitignore/blob/master/Python.gitignore

So instead of shortening this list, I suggest to give credits to that file (transfer the responsibility :wink:)
