### ISSUE TITLE
Template must contain `results/` dir

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#176]
since Makefile explicitly accesses it: 
https://github.com/neuromation/cookiecutter-neuro-project/blob/780d1aa8f174b7f786e0561ef2c8af2c4decc558/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L6

+ need tests

**Comment by mariyadavydova** [comment]
I didn't add this folder on purpose, assuming that one doesn't want to download logs and keep them in Git. This assumption may be wrong. If adding this folder, we should also add corresponding Makefile goal to download the content of this folder.

**Comment by ayushkovskiy** [comment]
closed in https://github.com/neuromation/cookiecutter-neuro-project/pull/208
