### ISSUE TITLE
Change `--notebooks-dir` for `make jupyter`

### ISSUE THREAD

**Issue by yartem** [neuromation/cookiecutter-neuro-project#178]
https://github.com/neuromation/cookiecutter-neuro-project/blob/780d1aa8f174b7f786e0561ef2c8af2c4decc558/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L152

maybe `--notebooks-dir=$(PROJECT_PATH_ENV)/$(NOTEBOOKS_DIR)`?

**Comment by mariyadavydova** [comment]
It was `--notebooks-dir=$(PROJECT_PATH_ENV)/$(NOTEBOOKS_DIR)` initially, and then we changed it to `--notebooks-dir=$(PROJECT_PATH_ENV)`. Don't you remember why?
