### ISSUE TITLE
Rename command `make kill` -> `make kill-all`

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#181]
so that not to kill all your jobs by mistake.

cc @Rauf-Kurbanov, @mariyadavydova

**Comment by mariyadavydova** [comment]
I second that.

**Comment by ayushkovskiy** [comment]
Also, according to @AlekseySh, other commands `make upload` & `make clean` should be postfixed with `-all` as well, see https://docs.google.com/document/d/13c_eYG2v4wNnp9RIhE_gXCSTvEw_i_HQzK7djEsSOjw/
