### ISSUE TITLE
Simplify env var: `CUSTOM_ENV_NAME`

### ISSUE THREAD

**Issue by yartem** [neuromation/cookiecutter-neuro-project#185]
we don't have a term "env" or "environment' in Neuro terminology, we call them "images" as docker. Let's drop var `BASE_ENV_NAME` (I don't think someone will need to overload it) and have a single var `BASE_IMAGE` or even `IMAGE`

**Comment by mariyadavydova** [comment]
Disagree. In our attempt to hide Docker details from our users, I used the word "environment" throughout docs instead of "image". Actually, an "image" doesn't mean anything but picture files for a user if they don't have Docker experience.

**Comment by ayushkovskiy** [comment]
> Disagree. In our attempt to hide Docker details from our users,

it does not go along with neuro CLI terminology: see `neuro image list`, `neuro run ... image:my-img`

However, I agree that in Template, we try to hide this image. Still, I want to shorten `BASE_ENV_NAME`. How about `BASE_ENV`?
