### ISSUE TITLE
Automate upgrade of existing projects

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#186]
We had [this ugly PR](https://github.com/neuromation/cookiecutter-neuro-project/pull/183) as an attempt to semi-automate the process of updating template in existing projects. @mariyadavydova [has pointed out](https://github.com/neuromation/cookiecutter-neuro-project/pull/183#issuecomment-559050831) that it's more reasonable to have a make target that uses `cookiecutter --config-file` instead of automating it with `expect`. I like the idea very much.

Plan:
0. When cookiecutting a new project, create a config for the project, like: `cookiecutter.yml` that would remember user's preferences (project name, proejct slug, etc)
1. Add a make target `make update-template`
1.1 it should run `cookiectuter` using htis config
2. test it (also in case if the config doesn't exist as it'll be the case for all existing projects)
3. Add instructions 
3.1 ... that encourage users to use git to track changes, because they would need to manually fix Makefile after the update (resolve conficts between their changes and the updated Template).
3.2 also describe what exactly does `make update-template` and what changes will occur.

**Comment by mariyadavydova** [comment]
I opt for this feature very much. I would even ask to raise its priority and do it before any other template changes to simplify further updates of ML recipes.

**Comment by ayushkovskiy** [comment]
Closed by https://github.com/neuromation/cookiecutter-neuro-project/pull/344
