### ISSUE TITLE
Split README.md into two files

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/cookiecutter-neuro-project#234]
* `README.md` should contain a placeholder for description, a Quick Start section (as in Recipes), and a reference to `HELP.md`.
* `HELP.md` should contain all information about directories structure, data manipulation, available commands, etc.

This change will make it easier to apply Cookiecutter template updates to the projects. Also, it will have the most relevant information in README.md, keeping it short.

**Comment by ayushkovskiy** [comment]
closed by https://github.com/neuromation/cookiecutter-neuro-project/pull/345
