### ISSUE TITLE
Expand commands options in Makefile

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#24]
Since one of the purposes of the Makefile is to teach users to work with neuro, let's use full options instead of short options.

Example: `neuro cp -r -p -u -T $(DATA_PATH) $(DATA_PATH_STORAGE)` -> `neuro cp --recursive --progress --update --no-target-directory $(DATA_PATH) $(DATA_PATH_STORAGE)`

**Comment by mariyadavydova** [comment]
Agree. I used full option names in the JOBS section and forgot to update other commands.
