### ISSUE TITLE
Add information to README.md inside the template

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/cookiecutter-neuro-project#25]

**Comment by astaff** [comment]
After a few iterations of applying our template to various projects and having to document that for others, I came up with the following. Feel free to re-use any of the parts.

# Project Title

Project description.

# Development Environment

This project is designed to run on [Neuro Platform](https://neu.ro), so you can jump into problem-solving right away.

## Directory Structure

| Mount Point              | Description                       | Storage URI                     |
|:------------------------ |:--------------------------------- |:------------------------------- |
|`/project/data/`          | Identities and test images        | `storage:face-id/data/`         |
|`/project/face-id/`       | Python modules                    | `storage:face-id/face-id/`      |
|`/project/notebooks/`     | Jupyter notebooks                 | `storage:face-id/notebooks/`    |
|`/project/requirements/`  | pip and apt-get packages required | `storage:face-id/requirements/` |
|`/project/results/`       | Logs and results                  | `storage:face-id/results/`      |


## Development

Follow the instructions below to setup the environment and start Jupyter development session backed by CPU or GPU.

### Neuro Platform

* Setup development environment `make setup`
* Run Jupyter with GPU: `make jupyter`
* TBD: Run Jupyter with CPU: `make jupyter-cpu`
* Kill Jupyter: `make kill_jupyter`
