### ISSUE TITLE
Install modules defined in .py files during make setup

### ISSUE THREAD

**Issue by astaff** [neuromation/cookiecutter-neuro-project#29]
Currently we are only installing requirements, without installing project code as a package

**Comment by anayden** [comment]
We don't upload project code in `make setup`, there's a separate make task for that: `make upload-code`.
Shall we change that? Or shall we install package in `make upload-code`? Or something else?

Also cc @mariyadavydova

**Comment by mariyadavydova** [comment]
@astaff Could you please clarify why we should install the project code on a platform? 

AFAIU, this would be an essential step if we enforce people to write some kind of console apps (so that you run 'benchmark --data <path>' instead of 'python train.py --data <path>'), but right now we do not go for it. Please, correct me if I'm wrong.

**Comment by asvetlov** [comment]
Install a package is a bad idea when default `modules` is used, in this case generated `setup.py` should be omitted.
It can be desirable if something non-default is specified the template can generate a full-fledged package.

**Comment by mariyadavydova** [comment]
OK. Then, if we keep `modules` as default (at least, in the current version of the template), let's omit installation. If a user wants to install the package, they can always update a Makefile.

I suggest to postpone this task, unless someone has strong concerns.

**Comment by astaff** [comment]
The use case is the same as here: https://github.com/microsoft/nlp, for example

I see two scenarios:
1. Notebooks play the role of UI with utility modules/classes/functions stored as `.py` files in 'some-expectable-name-that-doesnt-change-much/*.py`. In order to use them in notebook you write: `from modules import function`.
2. This call is called from CLI for training, or as a part of hypter parameter search as `python -m modules.train` or even as `train` if we do the `setup.py` the right way.

In either case, Jupyter notebook session or training session depends on the source code being stored in one folder and synced with the remote environment.

We should take care of establishing this framework as the part of the template and do it in the most pythonic way, while keeping user intents and relevant work in mind.

**Comment by mariyadavydova** [comment]
OK, your arguments convince me, @astaff.

**Comment by asvetlov** [comment]
Artyom, `python -m modules.train` works without `setup,py`.
`setup.py` assumes unique library name and package path, if you are using *pythonic* word :)
