### ISSUE TITLE
Develop job works only 1h with large-gpu preset

### ISSUE THREAD

**Issue by atselousov** [neuromation/cookiecutter-neuro-project#318]
A develop job with `large-gpu` preset works only `1h` for me (it does not depend on `JOB_LIFETIME` value). After `1h` every job is closed with 124 error. This behavior has been continuing since Friday, when I changed preset specifications to `large-gpu`.
`neuro status` for one of the jobs:
![Screenshot from 2019-12-27 11-58-10](https://user-images.githubusercontent.com/22117239/71579103-16c78d80-2b0c-11ea-89c6-a936be1d8914.png)
but a job console output ends with 137 error (even if just `bash` is run):
![Screenshot from 2019-12-27 11-56-18](https://user-images.githubusercontent.com/22117239/71579199-8b023100-2b0c-11ea-9c65-d87798143562.png)

A job works `1h` if `JOB_LIFETIME` is set to `0` or `1d`. It did not change anything for me. 
![Screenshot from 2019-12-27 14-00-55](https://user-images.githubusercontent.com/22117239/71579228-b38a2b00-2b0c-11ea-940c-61f9dcedf5f9.png)

I inited my project with the previous Monday version of `cookiecutter-neuro-project` (commit ae76d6b129a7bc908343b38923fd05700241adfb).

**Comment by mariyadavydova** [comment]
The option is incorrect. It should be `--env JOB_TIMEOUT=1d`.
