### ISSUE TITLE
Terminal size of develop job

### ISSUE THREAD

**Issue by atselousov** [neuromation/cookiecutter-neuro-project#325]
Is it supposed that terminal after connecting to a job with the command `neuro exec --no-key-check JOB_NANE bash` will have the same terminal size as a local machine has? Example:

* Terminal size on the local machine:

![Screenshot from 2020-01-16 21-02-39](https://user-images.githubusercontent.com/22117239/72550334-9642b400-38a3-11ea-8104-4fab088c114a.png)

* Terminal after connection to a job with `neuro exec JOB_NANE bash`:

![Screenshot from 2020-01-16 12-36-15](https://user-images.githubusercontent.com/22117239/72550434-c8541600-38a3-11ea-9089-34ce48d896ab.png)

In this case, there is no problem with the terminal size. Terminal size on local and remote machines are equal. But sometimes, terminal size is equal to zero, for example, here:

![Screenshot from 2020-01-16 19-17-32](https://user-images.githubusercontent.com/22117239/72550593-1d902780-38a4-11ea-9edf-9afb85a2ab5c.png)

It affects how typed in terminal commands are displayed. During typing command starts overwriting itself, when there is not enough place.

I figured out, that it can be fixed with `tmux`. For it, you need to run `neuro exec` in `tmux` pane, split it vertically, and close the new pane. But another problem appears there. After fixing the terminal size this way, the `tmux` pane has an empty buffer, and it makes impossible to scroll up and see terminal outputs.

**Comment by ayushkovskiy** [comment]
Thank you for this issue! This is the question of `neuro`, I'll redirect it there.

**Comment by ayushkovskiy** [comment]
Will be considered in https://github.com/neuromation/platform-client-python/issues/1437
