### ISSUE TITLE
Having separate develop and jupyter targets seems excessive

### ISSUE THREAD

**Issue by Rauf-Kurbanov** [neuromation/cookiecutter-neuro-project#352]
I am debugging my code connecting to jupyter job anyway

**Comment by ayushkovskiy** [comment]
@atselousov @AlekseySh @mariyadavydova Let's vote: Should we drop targets `develop*` or not (they are almost identical to `train*`).

My opinion: we should drop them since the user will add customized necessary targets if needed.

**Comment by AlekseySh** [comment]
1 vote to not dropping it

**Comment by mariyadavydova** [comment]
My opinion: we should NOT drop them, as they have a different purpose than training (they should simply hold an SSH connection to the training environment).

**Comment by mariyadavydova** [comment]
So, 3 against 2 to for keeping the targets.

**Comment by Rauf-Kurbanov** [comment]
You can start jupyter notebook as default on develop instead of `sleep infinity`
And that you can redesign jupyter target, to simply run `neuro job browse` in case the develop is already up and start the develop job otherwise
