### ISSUE TITLE
Add 'jupyter-cpu' and 'kill-jupyter-cpu' targets

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/cookiecutter-neuro-project#37]
They should be similar to 'jupyter' and 'kill-jupyter', but run on 'cpu-small' preset.
Also, kill 'jupyter-cpu' job in 'kill' target.

**Comment by anayden** [comment]
We have the same issue for all targets, e.g. `training`. I think we need a solution for all of them.

Maybe, add a variable to the make file, something like `MACHINE_TYPE` with values `cpu`/`gpu`? This would control all of our jobs.

What do you think?

**Comment by mariyadavydova** [comment]
Well, different apps and different tasks require different resources:

* `setup` requires `cpu`
* `training` for visual tasks requires `gpu` or `tpu`, while for NLP one uses `cpu` or `tpu`
* `jupyter` may require `cpu`, `gpu`, or even `tpu`, depending on the way one uses it
* `tensorboard` requires `cpu`
* `filebrowser` requires `cpu`

Given that, I suggest adding a `TRAINING_MACHINE_TYPE`, default it to `gpu-small`, and use it in `training` and `jupyter` targets. Other job targets should use `cpu-small`.
