### ISSUE TITLE
Refine template parameters

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/cookiecutter-neuro-project#38]
Look at the following output:
```
full_name [Your name]: Mariya Davydova
email [Your email address (e.g. you@example.com)]: mariya.davydova@neuromation.io
project_name [Name of the project]: neuro-tutorial
project_slug [neuro-tutorial]: 
project_short_description [A short description of the project]: Tutorial
code_directory [modules]: rnn
Select year_from:
1 - 2019
Choose from 1 (1) [1]: 
year_to [2019]: 
Select license:
1 - BSD 2-Clause License
2 - BSD 3-Clause License
3 - MIT license
4 - ISC license
5 - Apache Software License 2.0
6 - no
Choose from 1, 2, 3, 4, 5, 6 (1, 2, 3, 4, 5, 6) [1]: 3
```
Some fields are hard to understand, like year_from and year_to. 
Other fields have strangely looking option selector, like licence.

**Comment by anayden** [comment]
@mariyadavydova could you please clarify how license selector should look like?

As far as `year_from` and `year_to` are concerned I wonder how you would suggest to name them? Something like `license_first_year`, `license_last_year` (this doesn't make much sense to me, just an idea)?

**Comment by mariyadavydova** [comment]
These years are pretty confusing anyway. Let's simplify the template for now, hardcoding 2019 as licence year?

```
full_name [Your name]: Mariya Davydova
email [Your email address (e.g. you@example.com)]: mariya.davydova@neuromation.io
project_name [Name of the project]: neuro-tutorial
project_slug [neuro-tutorial]: 
project_short_description [A short description of the project]: Tutorial
code_directory [modules]: rnn
Select license:
1 - BSD 2-Clause License
2 - BSD 3-Clause License
3 - MIT license
4 - ISC license
5 - Apache Software License 2.0
6 - no
Choose from 1, 2, 3, 4, 5, 6 (1, 2, 3, 4, 5, 6) [1]: 3
```

Also, can you add *both* a hint (like 'A name of the project') and a default value (like 'modules') fo the same template parameter?

**Comment by anayden** [comment]
> Also, can you add both a hint (like 'A name of the project') and a default value (like 'modules') fo the same template parameter?

No, it's impossible :(

**Comment by mariyadavydova** [comment]
That's a pity...
