### ISSUE TITLE
Integrate project with secrets

### ISSUE THREAD

**Issue by anayden** [neuromation/cookiecutter-neuro-project#399]
The goal is to replace current mechanism of sharing GCP, AWS and W&B credentials via files with secrets.

Implementation idea is to add make target parameter allowing users to specify which secrets to use for these services. Something along the lines of :
```
make develop SECRETS="GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/gcp.json AWS_CONFIG_FILE=/var/secrets/aws.txt"
```

**Comment by yartem** [comment]
How about shorten var names and use secret names instead of files:
```
$ neuro secret add gcp-secret --from-file=./file.txt
$ neuro secret add aws-secret --from-file=./file.txt
$ make develop SECRETS="GCP=gcp-secret AWS=aws-secret"
```

**Comment by anayden** [comment]
As discussed with @mariyadavydova we're going to fallback to the original option — `SECRETS` variable that's added to all `neuro run` calls.
