### ISSUE TITLE
Setup terminates after pip install during neuro save

### ISSUE THREAD

**Issue by astaff** [neuromation/cookiecutter-neuro-project#42]
Reproducible in this repo: https://github.com/neuromation/course-fastai-nlp.git

```
> make setup
...
<   Found existing installation: matplotlib 3.1.1
    Uninstalling matplotlib-3.1.1:
      Successfully uninstalled matplotlib-3.1.1
  Found existing installation: scikit-learn 0.21.3
    Uninstalling scikit-learn-0.21.3:
      Successfully uninstalled scikit-learn-0.21.3
command terminated with exit code 137
Connection to ssh-auth.neuro-ai.org.neu.ro closed.
make: *** [Makefile:48: setup] Error 137
```

**Comment by anayden** [comment]
@astaff I don't have access to the repo. Unable to reproduce otherwise

**Comment by mariyadavydova** [comment]
@anayden I gave use access.

**Comment by anayden** [comment]
Looks like image name is set incorrectly here: https://github.com/neuromation/course-fastai-nlp/blob/master/Makefile#L30

It should say `image:neuromation-course-fastai-nlp`. Works for me when I update the variable.

Cookiecutter sets variable name correctly, not sure how it ended up invalid in the repo.

**Comment by astaff** [comment]
Changing it to `image:neuromation-course-fastai-nlp` didn't help. I did try to isolate the problem by running:
```
neuro --network-timeout 300 job save setup image:neuromation-course-fastai-nlp
```
And got:
```
Saving job-7423db67-a9b3-484c-83f8-8b6ca9922a67 -> image://astaff/neuromation-course-fastai-nlp:latest
ERROR: Expecting value: line 1 column 1 (char 0)
```

I have another track here: https://github.com/neuromation/platform-client-python/issues/1057 for context (cc: @ayushkovskiy )

I am hearing the environment is an issue (i am in `neuro-ai`). How do I switch back to `neu.ro` and how do we get `neuro-ai` in the same state as `neu.ro` (cc @dalazx )

**Comment by anayden** [comment]
Yeah, that looks like the same issue. In order to switch to `neu.ro` you would `neuro logout` and `neuro login`.

**Comment by dalazx** [comment]
we deployed the most recent version of monitoring to all our envs. could someone please try again?
