### ISSUE TITLE
`neuro job save --network-timeout` is no longer needed

### ISSUE THREAD

**Issue by dalazx** [neuromation/cookiecutter-neuro-project#50]
https://github.com/neuromation/cookiecutter-neuro-project/blob/d0250513234d592b25ffb18edb50e11200e93a42/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L70

`--network-timeout` is irrelevant once https://github.com/neuromation/platform-client-python/pull/1062 is released.

**Comment by mariyadavydova** [comment]
@dalazx Can you please explain what happens in that fix? I mean, from UX point of view?

**Comment by dalazx** [comment]
@mariyadavydova that fix prevents `save` from timing out unexpectedly.

**Comment by Rauf-Kurbanov** [comment]
@dalazx is this fix already deployed?

**Comment by dalazx** [comment]
the fix in on the client side. it will be available with the next version of `neuromation`.

**Comment by Rauf-Kurbanov** [comment]
Is `--network-timeout` still relevant in 19.9.10 ?

**Comment by dalazx** [comment]
the next version. `--next-timeout` will become irrelevant for `save` only.

**Comment by Rauf-Kurbanov** [comment]
Thank you

**Comment by ayushkovskiy** [comment]
This fix is released in version 19.9.23, so current issue can be considered.
