### ISSUE TITLE
Improve help message on `make setup`

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#66]
The `make help` message needs more information on what's happening during `make setup`:
- where the project name (which the user chooses) is used (and also its derivatives, like the one defined by transformation: `project_name.lower().replace(" ", "_").replace("-", "_")`),
- which directories (locally, on storage) are created,
- which images are created/pulled

**Comment by mariyadavydova** [comment]
I suggest using cookiecutter hooks (#104) for this: we may print help messages explaining what is going to be done (pre-hook) and what's next (post-hook).

**Comment by mariyadavydova** [comment]
I address this in #87, adding this information in README.

**Comment by ayushkovskiy** [comment]
closed in https://github.com/neuromation/cookiecutter-neuro-project/pull/146
