### ISSUE TITLE
Handle invalid project names correctly

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#68]
We need to handle correctly projects with names that contain characters invalid for Python module name (`Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability.` https://www.python.org/dev/peps/pep-0008/). 

Currently, we allow some invalid names (for example, we allow names with dashes), but some features may be broken in future (for example, `make lint` will fail with `detection-kit is not a valid Python package name`).

**Comment by anayden** [comment]
Do you suggest replacing dashes with underscores? Would that be enough to cover most cases?

**Comment by ayushkovskiy** [comment]
I suppose, yes

**Comment by ayushkovskiy** [comment]
I think, these checks should be implemented via hooks https://github.com/neuromation/cookiecutter-neuro-project/issues/104
