### ISSUE TITLE
Change Makefile variables order

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/cookiecutter-neuro-project#86]
Put them in the following order:
* The variables that have to be changed (like TRANING_COMMAND)
* The variables that are likely to be changed (like DISABLE_HTTP_AUTH)
* The variables that may be changed (like paths and job names)
* The variables that are unlikely to be changed (like APT_COMMAND)

Add comments to the first two groups.

**Comment by ayushkovskiy** [comment]
closed in https://github.com/neuromation/cookiecutter-neuro-project/pull/146
