### ISSUE TITLE
Refine template parameters [again]

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/cookiecutter-neuro-project#88]
Let's use descriptive names and values instead of default values. 
For example: `code_directory [A valid python module name, e.g. "modules"]`.

**Comment by ayushkovskiy** [comment]
cookiecutter uses widely used (pardon) syntax of CLI utilities, by defining the default value in square brackets `[...]`. As this issue is quite common, there are attempts to extend the syntax for `cookiecutter.json`, though they all are in pending state (issues: https://github.com/cookiecutter/cookiecutter/issues/794, https://github.com/cookiecutter/cookiecutter/issues/30, PRs: https://github.com/cookiecutter/cookiecutter/pull/360, https://github.com/cookiecutter/cookiecutter/pull/848).

So I don't see a solution within bare cookiecutter. Perhaps, all we can do here is to explain all the fields in our documentation.

**Comment by ayushkovskiy** [comment]
Please note that currently the default `email` value is also not an e-mail (see field `author`):
```
setup(
    name='name-of-the-project',
    packages=find_packages(),
    version='1.0.0',
    description='A short description of the project',
    author='Your email address (e.g. you@example.com)',
    license='MIT',
)
```

**Comment by mariyadavydova** [comment]
OK, the current parameter list looks like this:

```
full_name [Your name]: Mariya Davydova
email [Your email address (e.g. you@example.com)]: mariya.davydova@neuromation.io
project_name [Name of the project]: Neuro Tutorial
project_slug [neuro-tutorial]: 
project_short_description [A short description of the project]: A simple tutorial.
code_directory [modules]: rnn
Select license:
1 - BSD 2-Clause License
2 - BSD 3-Clause License
3 - MIT license
4 - ISC license
5 - Apache Software License 2.0
6 - no
Choose from 1, 2, 3, 4, 5, 6 (1, 2, 3, 4, 5, 6) [1]: 3
```

Taking #92 and #67 in consideration, we may update them as follows:

```
author_name [Your Name]: Mariya Davydova
author_email [you@example.com]: mariya.davydova@neuromation.io
project_name [Your Project]: Neuro Tutorial
project_short_description [A short description of the project.]: A simple tutorial.
repo_name [neuro-tutorial]: 
package_name [modules]:
```

So,
* `author_name` and `author_email` are to be used in `setup.py` (#90) and `README.md` 
* `project_name` and `project_short_description` are to be used in `README.md`
* `repo_name` (former `project_slug`) is generated automatically from `project_name`
* `package_name` (former `code_directory`) is defaulted to `modules`

Does it make sense to you, @ayushkovskiy?

**Comment by ayushkovskiy** [comment]
@mariyadavydova Currently most of the elements work as you described:

> author_name and author_email are to be used in setup.py (#90) and README.md

just rename `full_name` to `author_name`, `email` to `author_email`

> project_name and project_short_description are to be used in README.md

they are currently used

> repo_name (former project_slug) is generated automatically from project_name

just rename `project_slug` to `repo_name`

> package_name (former code_directory) is defaulted to modules

just rename `code_directory` to `package_name`

**Comment by ayushkovskiy** [comment]
also: change `author_email` to the new valid default value

**Comment by anayden** [comment]
@ayushkovskiy are you going to fix #92 in this issue/PR? If not, I can do it separately, no big deal.

**Comment by ayushkovskiy** [comment]
@anayden yes not a big deal, let's do either

**Comment by ayushkovskiy** [comment]
So far this project is not as large as `platform-api`, so I think it's perfectly fine to save our time and not wait for tests on each tiny change, and do bigger PRs with more changes.

**Comment by mariyadavydova** [comment]
Now I think that we really need very few params, explained in help message (#66):
```
project_name [Your Project]: Neuro Tutorial
project_slug [neuro-tutorial]: 
code_directory [modules]:
```

**Comment by ayushkovskiy** [comment]
closed in https://github.com/neuromation/cookiecutter-neuro-project/pull/146
