### ISSUE TITLE
Update the year in LICENSE

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/cookiecutter-neuro-project#89]
Use the following construction:

```Copyright (c) {% now 'utc', '%Y' %}, {{ cookiecutter.author_name }}```

**Comment by asvetlov** [comment]
The license in a generated template makes harm, I guess it should be removed.
The root license is required, it is the license for cookiecutter-neuro-project.
But a license *inside* a template is related to *generated* code.
As a user, I cannot agree to apply MIT to my project. I may prefer Apache or GPL. Moreover, in very many cases my generated project is a part of proprientary job; it should have no license file or something very custom.

**Comment by mariyadavydova** [comment]
@asvetlov I looked at some popular cookiecutter templates, and they usually contain a LICENSE file inside the template. Moreover, they give you a choice between several types of licenses (as we do - we have five types of available licenses, plus empty license).

Overall when designing this template, I follow this rule: the solution should cover the majority of the use cases. ATM I assume that the choice of licenses we provide covers the majority of the use cases.

**Comment by asvetlov** [comment]
IMHO public templates are created by FOSS developers and oriented for themself. Do our users create mostly a public software or proprietary? The answer rules the default selection of license.

Anyway, if I choose "no" (which is number 6 currently) I have empty LICENSE file and "MIT" in `setup.py`. Not ideal.

Where is ISC license used outside of OpenBSD? Not sure if I can remember ever the single case.

P.S.
After a brief overview, I see other points where I disagree.
My job is hard enough even without this template project. 
If you've found that I'm too noisy here please let me know.

**Comment by ayushkovskiy** [comment]
@asvetlov Please don't feel any stress on expressing your opinion: your experience is extremely important and valuable for us, in particular for this project, which aims to consolidate Python best practices. 

@mariyadavydova I also think we should not make license decisions on behalf of users, especially as sensitive as legal questions, which theoretically might bring us legal problems in future. Assuming that all projects (even FOSS) are either empty and public or just private at the very beginning, let's delete LICENSE generation?

**Comment by asvetlov** [comment]
Thanks @ayushkovskiy 

You've expressed my worry in a very polite and clear manner :)

**Comment by mariyadavydova** [comment]
OK, I hear you both. Let's remove the LICENSE (#92).

My primary concern about the license is that folks often tend to forget adding it in public repositories, and a lot of noе-so-popular ML-related projects on GitHub do not have LICENSEs at all (which makes it hard to re-use their work). However, probably, it is not us and our template who have to solve this problem.

@asvetlov As @ayushkovskiy already said, your experience and opinion are precious for us, so please, do not hesitate to raise your concerns either in the form of issues and comments or in the form of personal chat, whichever you prefer.
