### ISSUE TITLE
Refactor setup.py

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/cookiecutter-neuro-project#90]
* Use author name and email.
* Use license name.

**Comment by ayushkovskiy** [comment]
@mariyadavydova currently we have the following `setup.py`:
```
setup(
    name='{{cookiecutter.project_slug}}',
    packages=find_packages(),
    version='1.0.0',
    description='{{cookiecutter.project_short_description}}',
    author='{{cookiecutter.email}}',
    license='MIT',
)
```
How do you expect the field `author` to be changed?

Discussion on `license`: https://github.com/neuromation/cookiecutter-neuro-project/issues/89

**Comment by mariyadavydova** [comment]
I would prefer to see the name and the email, like this:
```
      author='Flying Circus',
      author_email='flyingcircus@example.com',
```

**Comment by ayushkovskiy** [comment]
Thank you @mariyadavydova for the clarification.

By the way, I think we should use (in future) `neuro` user's name and, if possible, email.

**Comment by ayushkovskiy** [comment]
wait: what's then the difference between `author` and `full_name`? Currently, it's being asked the first:
```
full_name [Your name]: 
email [Your email address (e.g. you@example.com)]: 
project_name [Name of the project]: 
...
```

**Comment by ayushkovskiy** [comment]
Considering https://github.com/neuromation/cookiecutter-neuro-project/issues/88: the task is to rename `full_name` to `author_name`, `email` to `author_email`
