### ISSUE TITLE
Simplify Makefile

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/cookiecutter-neuro-project#96]
The following variables are used only once:
```
PROJECT_PATH_STORAGE?=storage:{{cookiecutter.project_slug}}
CODE_PATH_STORAGE?=$(PROJECT_PATH_STORAGE)/$(CODE_PATH)
DATA_PATH_STORAGE?=$(PROJECT_PATH_STORAGE)/$(DATA_PATH)
NOTEBOOKS_PATH_STORAGE?=$(PROJECT_PATH_STORAGE)/$(NOTEBOOKS_PATH)
REQUIREMENTS_PIP_STORAGE?=$(PROJECT_PATH_STORAGE)/$(REQUIREMENTS_PIP)
REQUIREMENTS_APT_STORAGE?=$(PROJECT_PATH_STORAGE)/$(REQUIREMENTS_APT)
RESULTS_PATH_STORAGE?=$(PROJECT_PATH_STORAGE)/$(RESULTS_PATH)

PROJECT_PATH_ENV?=/project
CODE_PATH_ENV?=$(PROJECT_PATH_ENV)/$(CODE_PATH)
DATA_PATH_ENV?=$(PROJECT_PATH_ENV)/$(DATA_PATH)
NOTEBOOKS_PATH_ENV?=$(PROJECT_PATH_ENV)/$(NOTEBOOKS_PATH)
REQUIREMENTS_PIP_ENV?=$(PROJECT_PATH_ENV)/$(REQUIREMENTS_PIP)
REQUIREMENTS_APT_ENV?=$(PROJECT_PATH_ENV)/$(REQUIREMENTS_APT)
RESULTS_PATH_ENV?=$(PROJECT_PATH_ENV)/$(RESULTS_PATH)
```
Let's not declare them, but instead just inline their values. Example:
Instead of:
```
.PHONY: upload-data
upload-data:  ### Upload data directory to the platform storage
	$(NEURO_CP) $(DATA_PATH) $(DATA_PATH_STORAGE)
```
We'll use:
```
.PHONY: upload-data
upload-data:  ### Upload data directory to the platform storage
	$(NEURO_CP) $(DATA_PATH) $(PROJECT_PATH_STORAGE)/$(DATA_PATH)
```
Or more readable:
```
.PHONY: upload-data
upload-data:  ### Upload data directory to the platform storage
	$(NEURO_CP) $(DATA_PATH) $(PROJECT_PATH_STORAGE)/data
```

**Comment by mariyadavydova** [comment]
The initial idea of these variables was that one may tune them according to one's setup (especially in case with `data` folder which is likely to be outside the project). Instead of removing these parameters I would rather change their order (see #86).

**Comment by ayushkovskiy** [comment]
Also we need of other ways of Makefile simplification (e.g., I suspect many `.PHONY` are redundant)

**Comment by ayushkovskiy** [comment]
Let's extend this issue to be more broad: simplify makefile.

1. too many variables
2. possibly redundant `.PHONY` in some places
3. too complicated [`DISABLE_HTTP_AUTH` code](https://github.com/neuromation/cookiecutter-neuro-project/blob/9613b9f56607183790d4d14ba91938be042a4a91/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L36-L40) (IMO it's better to allow users to set up the very variable `HTTP_AUTH?=--no-http-auth` because thus they learn more easily)
4. think more systematically, which variables we can expose
4.1 `NEURO_RUN_EXTRA_OPTS` for storing extra options of `neuro run`, and append this variable instead of having all these `TRAINING_MACHINE_TYPE`, `HTTP_AUTH`, etc.
4.2 either use only bare `neuro run` and `neuro cp`, or use only shortcuts `$(NEURO_RUN)`, `$(NEURO_CP)` (personally, I prefer the first option with `NEURO_{verb}_EXTRA_OPTIONS`)

**Comment by ayushkovskiy** [comment]
closed in https://github.com/neuromation/cookiecutter-neuro-project/pull/146
